### ISSUE TITLE
Support video files and more audio extensions

### ISSUE THREAD

**Issue by rgaudin** [openzim/nautilus#2]
ATM only ogg files (audio) triggers the modal dialog which renders using an `<audio />` node.
We should trigger this on most common audio extensions and we should also trigger it (although with `<video />` for video files.

**Comment by HAKSOAT** [comment]
Hello @rgaudin Is there some sort of processing we use that's just for `ogg` files at the moment? Such that if we allow other files may cause the code to break. Or is it just a case of allowing more extensions?

**Comment by rgaudin** [comment]
No, we use `video.js` which supports whatever the browser supports. In addition, we use `ogv.js` with `videojs-ogvjs` to support ogg audio and video.

this ticket is just to enable the audio/video player for most common audio and video extensions that one could you in a ZIM.

In the ZIM we create ourselves, we only use ogg because that's the only way to support all platforms but others are free to use regular formats like mp3/mp4.
