### ISSUE TITLE
Add apple seeking fix for videos

### ISSUE THREAD

**Issue by rgaudin** [openzim/nautilus#20]
As for youtube and ted

**Comment by dauinh** [comment]
Hi! What do you mean by "add apple seeking fix?"

**Comment by Nirav0702** [comment]
Can Anyone give me more info on this issue

**Comment by rgaudin** [comment]
See https://github.com/openzim/youtube/issues/91

**Comment by FledgeXu** [comment]
Is it still a bug? Since Safari 16, Safari should have supported webm. I just tested it in Safari 16.4 on macOS. it's totally fine.

**Comment by kelson42** [comment]
Good news, but would still recommend to use the player.

**Comment by rgaudin** [comment]
As with WebP, situtation differs between macOS and iOS…

**Comment by rgaudin** [comment]
Didn't do much as the webp trick is not necessary since we use no cover not webp and the rest of the fix is to reencode videos using new preset (nautilus doesn't encode anything)

**Comment by rgaudin** [comment]
Fortunately, even though we dont have the source videos anymore, reencoding previous webm does the trick
