### ISSUE TITLE
Zim file should indicate number of different pieces of content 

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus#22]
Currently all Nautilus-issued files indicate that they have only one article - they should rather indicate the number of files that are contained within them.

![Screenshot_20201112_151148_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/98956176-03dd6200-2500-11eb-923f-11b17ca2a44f.jpg)

**Comment by rgaudin** [comment]
It won't. This is an android issue that links back to a kiwix-lib issue about reporting only HTML articles (`/A` namespace in current/prev libzim). There are tickets on those repo about this.
