### ISSUE TITLE
Allow JSON "file" entry to be a string scalar

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#27]
Tha means that the `files` JSON entry could be an list OR a string. This would be helpful because the case of only one file per entry represents 99% of the cases and this is pretty hard for non-dev to create JSON list entries with a tool like `csv2json`.

**Comment by rgaudin** [comment]
Probably an easy fix but this is wrong IMO. This is not a UI. It's a scraper that takes a JSON as input. JSON is a strict format that requires rigorousness. Adapting the format so people can edit it easily or can convert easily from some tool is definitely not the right approach.

**Comment by kelson42** [comment]
I agree with your feedback. I will close the ticket. It is just that here we have a huge ratio between the effort and the result. I see no other easy alternative. Building a proper UI would probably need 1-2 weeks to build.

**Comment by rgaudin** [comment]
We can implement it. We just need to acknowledge that it stops there and any further accommodation would go through an appropriate UI.

**Comment by deepu-bansal** [comment]
hey , can i work on this issue?

**Comment by rgaudin** [comment]
Well, now that we are actually about to start a WebUI, Iet's close this ticket. Thank for bringing it to our attention though.
