### ISSUE TITLE
Inputs (in particular the collection.json) should be checked

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#29]
See #28. After many iterations we have achieved to buidl a ZIM, but the ZIM is incorrect and we have no clue why.

The check should, at start, verify that everything is OK (and reports/stops otherwise):
* Key inputs/files are downloadable
* Key values are available in the JSON
* JSON values are correct, in particular the `files`
* ...

**Comment by rgaudin** [comment]
This is mostly obsolete. JSON is the source of trust and entries are checked early.
Only recent URL entries are not completely checked

**Comment by kelson42** [comment]
@rgaudin I don't understand your last comment: do we check data in json are correct? If "yes, how? If "no",  why this doesnot matter?

**Comment by rgaudin** [comment]
JSON entries are either a references to a file in the ZIP archive (if using one) or an arbitrary URL.
If an URL, we check that the URL works (HTTP 200) ; if not, we check that it is indeed inside the ZIP.
