### ISSUE TITLE
zimgit-post-disaster_en recipe does not open files

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus#31]
The recipe yields a 730+ Mb file, so the content is likely to be there, however when clicking on the entries the screen gets stuck on `Loading`

![image](https://user-images.githubusercontent.com/21675885/145571194-f9d80e30-2ccf-4f6d-80bf-b6fe19e7d1a5.png)

**Comment by kelson42** [comment]
http://dev.library.kiwix.org/zimgit-post-disaster_en_2021-09/A/home.html works fine, we have somehow the bad json probably.

**Comment by rgaudin** [comment]
Was indeed using the wrong version of the collection. Fixed and relaunched. Updated recipe to use :dev so we benefit from the *random* indexDB name but please refresh browser.
