### ISSUE TITLE
How do we determine the order in which files appear

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus#32]
Looking at the [zimgit-collection.json](https://drive.farm.openzim.org/_admin/#/zimgit-post-disaster_en) I see that the order should be 

1. Three Days Emergency Preparedness,
2. 3 month supply of food, and
3. Water purification
(and so on)

but when opening the file I get 
1. Three Days Emergency Preparedness",
2. 3 month supply of food", and
3. How-to-Find-Your-Way

With `Water purification` being much farther down. I can't figure out any alphabetical order either, so I'm rather curious on how we should game the system to make sure we have docs coming in the right order

**Comment by rgaudin** [comment]
Use the `--no-random` option of the scraper ; that is exposed in the zimfarm.

**Comment by Popolechien** [comment]
Well `--no-random` was, in fact, [already enabled](https://farm.openzim.org/recipes/zimgit-post-disaster_en/edit). 

So either it did not work and we have a but, or ??
