### ISSUE TITLE
Trust collection as source for files

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus#33]

**Comment by rgaudin** [comment]
Currently, nautilus takes all files from the ZIP and add them to the ZIM file.
Then, it builds an index using the collections.json ; assuming there is a perfect match between in-ZIP paths and the collection.

A more user-realistic approach would be to trust the collection and work off it: for each file listed in the collection, extract the matching entry in ZIP and add it to the ZIM.

This will have the benefit of identifying early (by failing) when there is a mismatch between collection and ZIP content. It would also allow selections from the same ZIP file, without wasting space

**Comment by kelson42** [comment]
@rgaudin @Popolechien Not sure about the exact status of this issue as I don't fully understand it and is already pretty old. What should we do next?

**Comment by rgaudin** [comment]
Checked source code ; this has been implemented
