### ISSUE TITLE
zimcheck complains about one empty URL in homepage

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#35]
See for example at https://farm.openzim.org/pipeline/4dac054ef2508c39223c5d16/debug

**Comment by rgaudin** [comment]
This is not a nautilus bug. Nautilus write `<a href="home.html">` which zimwriterfs turns into `<a href="">`.

An empty link is a valid link and serves a purpose so I wouldn't consider this a zimwriterfs bug. Why would zimcheck complain about empty links? I understand how an erroneous link (unresolved) is problematic but not how empty ones could be. See [this SO post](https://stackoverflow.com/a/43340108/631925) for pointers to specs.

**Comment by kelson42** [comment]
@rgaudin Agree with your comment, an empty link should not be an error, a warning at best.
