### ISSUE TITLE
Credit page should not be a front page

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#38]
Or should be save as `raw` page, but for the moment this non-valid HTML find is part or the listing and can be found with random.

See http://192.168.178.24:8282/mesptitesquestions_fr_2022-01/A/files/about.html

**Comment by rgaudin** [comment]
Actually shouldn't be included as it is read to feed in something else.

Be aware though that nautilus being a bring-your-files-to-zim tool, it could contain HTML files that would be Content and thus findable by random, regardless of whether those are valid or not.
