### ISSUE TITLE
Scraper collects all files even when JSON points to a subset

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus#39]
I have a large number of files, which I have tried to break into different subsets. The JSON (and zim UI) only list  (and show) 10-15 files, but the zim contains all files that were in the source folder.

Ideally the zim file should only include files that are listed in the JSON.

**Comment by Popolechien** [comment]
I realize that this would entail unzipping the source zip, selecting the chosen files and re-zip them. Not really practical.

**Comment by rgaudin** [comment]
I don't understand the second comment but this issue is a duplicate of #33

Although it's right in this case, I'd prefer maintainers to add the good-first-issue label
