### ISSUE TITLE
In Kiwix-Desktop the handling of download is strange

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#4]
Whereas with a Gutenberg ZIM file (epub) it behaves properly. With the youscribe ZIM file, I have:
* A new tab open (should be none)
* Two files pickers open (should be only one)

**Comment by rgaudin** [comment]
As for the new tab, it will be fixed in nautilus. We open links using `target="_blank"`. It was done as PDF files open in-browser on most web browsers (kiwix-serve) and that seemed more practical but I think we should remove it.

Regarding the two file pickers, I'll try to reproduce.
