### ISSUE TITLE
Organize files in download.kiwix.org/zim/

### ISSUE THREAD

**Issue by Rexadev** [openzim/nautilus#44]
### 1. These same should be merged.

https://download.kiwix.org/zim/zimit/
https://download.kiwix.org/zim/other/

### 2. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Computer/Linux/Gentoo

[gentoo_en_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/gentoo_en_all_maxi_2021-02.zim) 
[gentoo_en_all_maxi_2021-03.zim](https://download.kiwix.org/zim/other/gentoo_en_all_maxi_2021-03.zim) 
[gentoo_en_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/gentoo_en_all_nopic_2021-02.zim) 
[gentoo_en_all_nopic_2021-03.zim](https://download.kiwix.org/zim/other/gentoo_en_all_nopic_2021-03.zim) 

[installgentoo_en_all_maxi_2019-09.zim](https://download.kiwix.org/zim/other/installgentoo_en_all_maxi_2019-09.zim)
[installgentoo_en_all_nopic_2019-09.zim](https://download.kiwix.org/zim/other/installgentoo_en_all_nopic_2019-09.zim)

### These to https://download.kiwix.org/zim/Computer/Linux/Arch

[   ] [archlinux_en_all_maxi_2022-03.zim](https://download.kiwix.org/zim/other/archlinux_en_all_maxi_2022-03.zim)  
[   ] [archlinux_en_all_maxi_2022-04.zim](https://download.kiwix.org/zim/other/archlinux_en_all_maxi_2022-04.zim)  
[   ] [archlinux_en_all_nopic_2022-05.zim](https://download.kiwix.org/zim/other/archlinux_en_all_nopic_2022-05.zim)
[   ] [archlinux_en_all_nopic_2022-09.zim](https://download.kiwix.org/zim/other/archlinux_en_all_nopic_2022-09.zim)

### These to https://download.kiwix.org/zim/Computer/Linux/Alphine
[   ] [alpinelinux_en_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/alpinelinux_en_all_maxi_2021-02.zim)  
[   ] [alpinelinux_en_all_maxi_2021-03.zim](https://download.kiwix.org/zim/other/alpinelinux_en_all_maxi_2021-03.zim)   
[   ] [alpinelinux_en_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/alpinelinux_en_all_nopic_2021-02.zim)   
[   ] [alpinelinux_en_all_nopic_2021-03.zim](https://download.kiwix.org/zim/other/alpinelinux_en_all_nopic_2021-03.zim)                          

### These to https://download.kiwix.org/zim/Computer/Web Development

[   ] [developer.mozilla.org_en_all_2022-03.zim](https://download.kiwix.org/zim/zimit/developer.mozilla.org_en_all_2022-03.zim)            
[   ] [developer.mozilla.org_en_all_2022-05.zim](https://download.kiwix.org/zim/zimit/developer.mozilla.org_en_all_2022-05.zim)   

### 3. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/VideoGaming/

[   ] [zdoom_en_all_maxi_2022-08.zim](https://download.kiwix.org/zim/other/zdoom_en_all_maxi_2022-08.zim) 
[   ] [zdoom_en_all_maxi_2022-09.zim](https://download.kiwix.org/zim/other/zdoom_en_all_maxi_2022-09.zim)   
[   ] [zdoom_en_all_nopic_2022-08.zim](https://download.kiwix.org/zim/other/zdoom_en_all_nopic_2022-08.zim)
[   ] [zdoom_en_all_nopic_2022-09.zim](https://download.kiwix.org/zim/other/zdoom_en_all_nopic_2022-09.zim)

### 4. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Computer/Android

[   ] [termux_en_all_maxi_2022-08.zim](https://download.kiwix.org/zim/other/termux_en_all_maxi_2022-08.zim) 
[   ] [termux_en_all_maxi_2022-09.zim](https://download.kiwix.org/zim/other/termux_en_all_maxi_2022-09.zim)

### 5. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/OtherLanguages/fr or de /Computer/Linux

[   ] [ubuntudoc_fr_all_2009-01.zim](https://download.kiwix.org/zim/other/ubuntudoc_fr_all_2009-01.zim) 
[   ] [ubuntudoc_fr_all_2015-12.zim](https://download.kiwix.org/zim/other/ubuntudoc_fr_all_2015-12.zim)    
[   ] [ubuntuusers_de_all_2013-03.zim](https://download.kiwix.org/zim/other/ubuntuusers_de_all_2013-03.zim)    
[   ] [ubuntuusers_de_all_2017-03.zim](https://download.kiwix.org/zim/other/ubuntuusers_de_all_2017-03.zim)      
[   ] [ubuntuusers_de_all_nopic_2017-03.zim](https://download.kiwix.org/zim/other/ubuntuusers_de_all_nopic_2017-03.zim)

### 6. https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Sports/Hicking

[   ] [hitchwiki_en_all_maxi_2022-02.zim](https://download.kiwix.org/zim/other/hitchwiki_en_all_maxi_2022-02.zim)   
[   ] [hitchwiki_en_all_maxi_2022-03.zim](https://download.kiwix.org/zim/other/hitchwiki_en_all_maxi_2022-03.zim)  
[   ] [hitchwiki_en_all_nopic_2022-02.zim](https://download.kiwix.org/zim/other/hitchwiki_en_all_nopic_2022-02.zim) 
[   ] [hitchwiki_en_all_nopic_2022-03.zim](https://download.kiwix.org/zim/other/hitchwiki_en_all_nopic_2022-03.zim)    

### 7. Moves these form https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Personal Development/

[   ] [artofproblemsolving_en_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/artofproblemsolving_en_all_maxi_2021-02.zim)
[   ] [artofproblemsolving_en_all_maxi_2021-03.zim](https://download.kiwix.org/zim/other/artofproblemsolving_en_all_maxi_2021-03.zim)
[   ] [artofproblemsolving_en_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/artofproblemsolving_en_all_nopic_2021-02.zim)
[   ] [artofproblemsolving_en_all_nopic_2021-03.zim](https://download.kiwix.org/zim/other/artofproblemsolving_en_all_nopic_2021-03.zim)

### 8. Moved these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/RegionSpecific/India/Educational

Also rename it diksha.gov.in

[   ] [diksha-std10ssc_mr_2020-11.zim](https://download.kiwix.org/zim/other/diksha-std10ssc_mr_2020-11.zim) 
[   ] [diksha-std5ssc_en_2020-11.zim](https://download.kiwix.org/zim/other/diksha-std5ssc_en_2020-11.zim) 

### 9. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Prepping/

[   ] [zimgit-food-preparation_en_2022-03.zim](https://download.kiwix.org/zim/other/zimgit-food-preparation_en_2022-03.zim)                        
[   ] [zimgit-knots_en_2022-03.zim](https://download.kiwix.org/zim/other/zimgit-knots_en_2022-03.zim)                  
[   ] [zimgit-medicine_en_2022-03.zim](https://download.kiwix.org/zim/other/zimgit-medicine_en_2022-03.zim)  
[   ] [zimgit-post-disaster_en_2022-01.zim](https://download.kiwix.org/zim/other/zimgit-post-disaster_en_2022-01.zim)    
[   ] [zimgit-post-disaster_en_2022-03.zim](https://download.kiwix.org/zim/other/zimgit-post-disaster_en_2022-03.zim)    
[   ] [zimgit-water_en_2022-03.zim](https://download.kiwix.org/zim/other/zimgit-water_en_2022-03.zim)              

For library.kiwix.org [zimgit-medicine_en_2022-03.zim](https://download.kiwix.org/zim/other/zimgit-medicine_en_2022-03.zim) belongs to Medicine Category to.     

### 10. Moves these from https://download.kiwix.org/zim/RegionSpecific/India/

Rename it zaya.org Education

[   ] [zaya-english-duniya-marathi_mr_2020-11.zim](https://download.kiwix.org/zim/other/zaya-english-duniya-marathi_mr_2020-11.zim) 

### 11.  Move these from https://download.kiwix.org/zim/zimit/ to https://download.kiwix.org/zim/Music/

[   ] [musictheory.net_en_all_2021-12.zim](https://download.kiwix.org/zim/zimit/musictheory.net_en_all_2021-12.zim)
[   ] [musictheory.net_en_all_2022-06.zim](https://download.kiwix.org/zim/zimit/musictheory.net_en_all_2022-06.zim)

### 12. Move These from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/AllTopic/

Rename to rationalwiki.org_en_*_*

[   ] [rationalwiki_en_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/rationalwiki_en_all_maxi_2021-02.zim) 
[   ] [rationalwiki_en_all_maxi_2021-03.zim](https://download.kiwix.org/zim/other/rationalwiki_en_all_maxi_2021-03.zim)        
[   ] [rationalwiki_en_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/rationalwiki_en_all_nopic_2021-02.zim)
[   ] [rationalwiki_en_all_nopic_2021-03.zim](https://download.kiwix.org/zim/other/rationalwiki_en_all_nopic_2021-03.zim)   

### 13. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Religion/Judiasm

[   ] [yeshiva_he_all_maxi_2020-12.zim](https://download.kiwix.org/zim/other/yeshiva_he_all_maxi_2020-12.zim)
[   ] [yeshiva_he_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/yeshiva_he_all_maxi_2021-02.zim) 
[   ] [yeshiva_he_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/yeshiva_he_all_nopic_2021-02.zim)  
[   ] [yeshiva_he_all_nopic_2021-03.zim](https://download.kiwix.org/zim/other/yeshiva_he_all_nopic_2021-03.zim)  

### 14. Move these to https://download.kiwix.org/zim/WikiMedia Projects

[DIR] [wikibooks/](https://download.kiwix.org/zim/wikibooks/)        
[DIR] [wikihow/](https://download.kiwix.org/zim/wikihow/)             
[DIR] [wikinews/](https://download.kiwix.org/zim/wikinews/)           
[DIR] [wikipedia/](https://download.kiwix.org/zim/wikipedia/)       
[DIR] [wikiquote/](https://download.kiwix.org/zim/wikiquote/)            
[DIR] [wikisource/](https://download.kiwix.org/zim/wikisource/)            
[DIR] [wikiversity/](https://download.kiwix.org/zim/wikiversity/)          
[DIR] [wikivoyage/](https://download.kiwix.org/zim/wikivoyage/)           
[DIR] [wiktionary/](https://download.kiwix.org/zim/wiktionary/)         

[wikispecies](https://download.kiwix.org/zim/other/wikispecies_en_all_maxi_2022-09.zim)

### 15. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Religion/Islam

[   ] [wikishia_fa_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/wikishia_fa_all_maxi_2021-02.zim)   
[   ] [wikishia_fa_all_maxi_2021-03.zim](https://download.kiwix.org/zim/other/wikishia_fa_all_maxi_2021-03.zim)    
[   ] [wikishia_fa_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/wikishia_fa_all_nopic_2021-02.zim)    
[   ] [wikishia_fa_all_nopic_2021-03.zim](https://download.kiwix.org/zim/other/wikishia_fa_all_nopic_2021-03.zim)   

### 16. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/Medicine/

[   ] [wikem_en_all_maxi_2021-01.zim](https://download.kiwix.org/zim/other/wikem_en_all_maxi_2021-01.zim)    
[   ] [wikem_en_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/wikem_en_all_maxi_2021-02.zim)   
[   ] [wikem_en_all_nopic_2021-01.zim](https://download.kiwix.org/zim/other/wikem_en_all_nopic_2021-01.zim)    
[   ] [wikem_en_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/wikem_en_all_nopic_2021-02.zim)    

### 17. Move these from https://download.kiwix.org/zim/other/ to https://download.kiwix.org/zim/TVShows/GameOfThrones

[   ] [westeros_en_all_2018-09.zim](https://download.kiwix.org/zim/other/westeros_en_all_2018-09.zim)  
[   ] [westeros_en_all_2018-10.zim](https://download.kiwix.org/zim/other/westeros_en_all_2018-10.zim)    
[   ] [westeros_en_all_maxi_2021-02.zim](https://download.kiwix.org/zim/other/westeros_en_all_maxi_2021-02.zim) 
[   ] [westeros_en_all_maxi_2021-03.zim](https://download.kiwix.org/zim/other/westeros_en_all_maxi_2021-03.zim)  
[   ] [westeros_en_all_nopic_2021-02.zim](https://download.kiwix.org/zim/other/westeros_en_all_nopic_2021-02.zim) 
[   ] [westeros_en_all_nopic_2021-03.zim](https://download.kiwix.org/zim/other/westeros_en_all_nopic_2021-03.zim)

**Comment by kelson42** [comment]
We don't organize ZIM files on download.kiwix.org based on topics, but mostly based on the techology/scraper used to build them.

Http://download.kiwix.org is anyway not the library. Https://library.kiwix.oeg is the library.

**Comment by Popolechien** [comment]
@kelson42 agree that download isn't the place, but what would be the best place to discuss the creation of new tags?

**Comment by kelson42** [comment]
@Popolechien Any tag can be put in the zim files at the zim creation

**Comment by Rexadev** [comment]
How about technology/Category/SubCategory/Site/.zim
@Popolechien

**Comment by rgaudin** [comment]
@Rexadev No I can't. This ticket is not appropriate as a feature-request on libkiwix as it is. You'd need to describe (there) what you're trying to achieve, why and how the current tools (library.kiwix.org and the API) are not satisfactory.
