### ISSUE TITLE
Need documentary to install and use Nautilus.

### ISSUE THREAD

**Issue by massifcoder** [openzim/nautilus#50]
I want to use this powerful tool, but I can not understand how to install it and then how to use it. For that can you guide me steps to use it, or provide documentary of Nautilus tool. I already read readme.md file but I can not get exact clearity that how I can use it over my PC. Please guide me .

**Comment by kelson42** [comment]
@massifcoder Duplicate of #51, be carrefuly to the quality of your tickets. I fyou keep open a lot of tickets which are not precise or duplicates, you might be blocked. Here a documentation about how to create a ticket https://github.com/openzim/overview/wiki/Report-a-bug

**Comment by rgaudin** [comment]
Just Re-read README; it's clear enough IMO. Do you have a more specific question?
