### ISSUE TITLE
Need help to install and use Nautilus tool.

### ISSUE THREAD

**Issue by massifcoder** [openzim/nautilus#51]
I want to use this powerful tool, but I can not understand how to install it and then how to use it. For that can you guide me steps to use it, or provide documentary of Nautilus tool. I already read readme.md file but I can not get exact clearity that how I can use it over my PC. Please guide me .

**Comment by kelson42** [comment]
@massifcoder Do you have any precise question about what you don't understand? Otherwise I will close the ticket like https://github.com/openzim/nautilus/issues/49#issuecomment-1468564587

**Comment by massifcoder** [comment]
I can not understand how to use this tool. How to install it. I fork the tool, now how what are steps to create a zim file.

**Comment by rgaudin** [comment]
If you can't figure it out from the README and the command line, it's probably not a tool for you.
