### ISSUE TITLE
Video content should be given with a wallpaper

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#55]
If I try to look to a video, I get this (before clicking on the "play" button)
![image](https://user-images.githubusercontent.com/1029718/236215869-effaa21d-7a70-40e3-a42a-8f93a3ae380a.png)

I want to have a proper image displayed in place of this grey box.

Either this is delivered in the json or we should find a way to capture one from the video stream.

**Comment by rgaudin** [comment]
The player displays the first frame of the video as cover. This series of videos happen to start with a blank grey image.

We could extract any random frame to create a dedicated thumbnail but we'd loose control over what gets picked up while every video tool uses the first frame (unless they allow choosing one). That's what's expected.

I am thus in favor of closing this. We could remove the blank frames and redo this ZIM as well.

<img width="1222" alt="Screenshot 2023-05-04 at 14 41 42" src="https://user-images.githubusercontent.com/57929/236242537-9443f4b9-0b23-43a6-bfba-d594218f8d55.png">

**Comment by kelson42** [comment]
Not sure how the solution should look like but I know we should not display a grey or black box for a video.

Using the first frame of a video is not what I expect, and it's not how it works usually. See Youtube, Netflix, etc.

I think the reason is obvious: it's just not what user expect, they want to get a picture which give an idea - is representive - of the content.

We should:
* either find a way to encourage publish to submit a poster
* find a smart algo to capture automatically a representive frame of the video

**Comment by rgaudin** [comment]
Closing in favor of #56 #57
