### ISSUE TITLE
Not working in Private Mode

### ISSUE THREAD

**Issue by rgaudin** [openzim/nautilus#6]
Since our PouchDB design relies on IndexedDB, we are dependent on IndexedDB working in the browser.

In Firefox, IndexedDB is disabled in Private Browsing mode. See [#781982](https://bugzilla.mozilla.org/show_bug.cgi?id=781982) and [#1562669](https://bugzilla.mozilla.org/show_bug.cgi?id=1562669). The latter shows that work is in progress to add support for it.

**Summary**: all currently available versions of Firefox can't use IDB in __private mode__ (and thus nautilus-based ZIMs). Chrome and Safari not affected ; apps not affected obviously.

**Questions**: Givent that, how much of a problem is that? @kelson42 @Popolechien

**Comment by Popolechien** [comment]
Looks like an edge case to me, we certainly can live with it.

**Comment by kelson42** [comment]
Same here, I would keep the ticket open for now, but not a priority to fix.

**Comment by kelson42** [comment]
New upstream ticket https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

**Comment by Jaifroid** [comment]
Still an issue in Firefox 113.02.

**Comment by rgaudin** [comment]
Bug is still open upstream (with activity):

- https://bugzilla.mozilla.org/show_bug.cgi?id=781982
- https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

Looks like it should arrive relatively soon: https://bugzilla.mozilla.org/show_bug.cgi?id=1831058

**Comment by kelson42** [comment]
The problem has been fixed upstream and it works now (on recent browsers)

See:
![image](https://github.com/openzim/nautilus/assets/1029718/5c946444-cf5a-49e0-8c8d-acadda84dced)

I don't think we should/could reasonably do anything more
