### ISSUE TITLE
Use python-scraperlib shared logic to handle description and long_description

### ISSUE THREAD

**Issue by benoit74** [openzim/nautilus#64]
See https://github.com/openzim/python-scraperlib/issues/110 once implemented

**Comment by HimaTeju** [comment]
@benoit74 Is this issue fixed? Because [here](https://github.com/openzim/overview/issues/21/) it is mentioned upgrade to 3.x already done.

**Comment by benoit74** [comment]
No, issue still needs to be done. Upgrade to 3.x is already done like mentioned, but the upgrade of python-scraperlib still has to be done, including supporting description and long_description with the new `compute_descriptions` function introduced in python-scraperlib.

It is very important to note that first thing to do is hence to start the scraper locally and understand how it works, and observe the ZIM content with current codebase. Once the upgrade will be done, you will have to do the same and confirm there is no regression. We won't accept PR without details of manual tests executed.

**Comment by HimaTeju** [comment]
I don't know if this is the best place to enquire about this but, What is the best way to work with these Repos? I'm on windows 11, I got suggestions from the Slack community to use WSL. Can I use Docker or WSL is the best to work on this? (I'm new to Linux also)

**Comment by rgaudin** [comment]
WSL will allow you tu setup the dev environment directly. You can also install and use docker inside WSL I believe

**Comment by HimaTeju** [comment]
Thank you!
