### ISSUE TITLE
Clear Search Button in Reading

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#67]
From kiwix-android created by [Sagar0-0](https://github.com/Sagar0-0): kiwix/kiwix-android#3658  

**Is your feature request related to a problem? Please describe.**

I searched for a query and found the results but after that, I wanted to clear the search and get the whole list. Sadly, there was no button to clear the search filter and get back to the default state.
![photo_6107086600765814465_y](https://github.com/kiwix/kiwix-android/assets/85388413/13643c88-2412-4350-91ff-f90bd0254576)

**Describe the solution you'd like**

When we have the same query we can have the clear button instead of the search button. 

**Describe alternatives you've considered**

An alternative could be to use the cross(x) button in the text field to clear the search query and list.

**Comment by rgaudin** [comment]
@Sagar0-0 There is one when the text field is highlighted. Just tested with latest android nightly.

Please confirm. I'll close in the mean time.

Works in a similar way in https://library.kiwix.org/viewer#prunelle_budding_authors_en_2023-05/home except android version uses a dark theme which is making the logo disappear with this particular ZIM.
