### ISSUE TITLE
HTML homepage template variables not filled properly

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#68]
To reproduce the following screenshot, just click on top left « home » logo:
<img width="1024" alt="image" src="https://github.com/openzim/nautilus/assets/1029718/c49975cb-ac14-4e0d-abeb-0306d04c45dd">

I expect search boxes (ZIM) are « ugly »

**Comment by rgaudin** [comment]
I believe the expectation is met then 😂

**Comment by rgaudin** [comment]
The link points to `home.html` instead of `home`. That's the issue.

**Comment by rgaudin** [comment]
Duplicate of #66
