### ISSUE TITLE
Unable to read all PDF pages on iOS FF (with Kiwix Serve)

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#71]
I can display any PDF first page:
<img width="1024" alt="image" src="https://github.com/openzim/nautilus/assets/1029718/6761a9f1-2488-41e8-930f-62630743ab2a">

… but when I swap down, nothing happens… I’m stuck at the first page.

Remark: not problem with Kiwix iOS.

**Comment by rgaudin** [comment]
It's an issue with the in-browser (Webkit for iOS) PDF reader that doesn't exposes those controls in the kiwix-serve iframe. It works as expected on the `/content/` endpoint.

Might be worth investigating an upstream (libkiwix) bug but I think it's reasonnable to _fix_ here with `target="blank"` as well.
