### ISSUE TITLE
youscribe_xxx ZIMs are not working anymore

### ISSUE THREAD

**Issue by benoit74** [openzim/nautilus#72]
All 3 youscribe ZIMs are faulty.

See https://github.com/openzim/zim-requests/issues/946 for details, but it looks like a scraper issue.

**Comment by rgaudin** [comment]
Re-ran the recipe with latest release, it works as expected. Must have been a v1.0.8 bug.

https://dev.library.kiwix.org/viewer#youscribe_fr_primaire_2024-03/home
