### ISSUE TITLE
Wrong number of files in zim description

### ISSUE THREAD

**Issue by Popolechien** [openzim/nautilus#8]
See screenshot: the file text description for "ressources éducatives" states 1400 and 1000 files available respectively, but the meta data indicates 1 file only
![Screenshot_20200227_180647_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/75467910-a5318180-598c-11ea-8632-86d728728363.jpg)

**Comment by rgaudin** [comment]
It doesn’t indicate 1 file but one article which is the number of files in
the /A namespace of the ZIM. this never includes media files.

**Comment by Popolechien** [comment]
Well can we fix this (as in rename issue to "metadata should indicate number of files") or is it a broader openzim issue and outside of scope for nautilus?

**Comment by kelson42** [comment]
@Popolechien This is outside the scope of Nautilus. The problem here is that Android does not display the number of media files (but only the number of articles).

**Comment by Popolechien** [comment]
OK no problem. So when looking at library.kiwix.org what does the 3 media files correspond to?

**Comment by kelson42** [comment]
@Popolechien Probably pictures... might be also to improved in an other way.
